[package]
name = "aletheia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.132", features = ["derive"] }
strum = "0.23"
strum_macros = "0.23"
serde_json = "1.0.73"

[dependencies.serde_with]
version = "1.11.0"
features = [ "default" ]